### PR TITLE
Add -fno-plt to the compiler flags, if supported.  (#71)

### PR DESCRIPTION
**Pull request by besser82**
Do not use the PLT for external function calls in position-independent code.  Instead, load the callee address at call sites from the GOT and branch to it.  This leads to more efficient code by eliminating PLT stubs and exposing GOT loads to optimizations.

Since we are already using -Wl,-z,now to disable lazy binding, the only downside (on x86-64) is that call instructions targeting C library functions are now six bytes each, instead of five bytes.

Closes: #71

### CODE REVIEW

**Comment by besser82** [comment]
@zackw The two functions are provided in your `zw_simple_warnings.m4`…

Shall I remove them there and include the original files instead?

**Comment by zackw** [comment]
@besser82 Huh. I don't remember why I did that. Now that there's more than one use it probably makes sense to move toward keeping things the way the autoconf archive has them.  (zw_simple_warnings.m4 really is an improvement on ax_manywarnings.m4 IMO, but only the part that actually picks warnings to activate, not the infrastructure.)

**Comment by zackw** [comment]
Since I'm still too busy with the day job to do any actual work on libxcrypt myself right now, you should do however much cleanup you feel is worth doing.

**Comment by besser82** [comment]
Merged via https://github.com/besser82/libxcrypt/commit/4b4aaa2241aa8b8d52e78cbf486acb0d8cb1e67d.

**Pull request closed without merging**
