### PR TITLE
ALT changes potentially useful for other vendors migrating from glibc's libcrypt

### PR DESCRIPTION
**Pull request by ldv-alt**
This series is a bare minimum of changes necessary to migrate from ALT glibc's libcrypt.  Other vendors might find it useful, e.g. `--enable-weak-hashes=glibc --enable-obsolete-api=glibc` seems to be a good choice for Fedora.

### CODE REVIEW

**Comment by ldv-alt** [comment]
The travis-ci based regression test is too flakey.

**Comment by zackw** [comment]
This pull request has a lot of different things mixed up together in it, so I'm going to review commit-by-commit.  I'd appreciate it if you could submit an independent PR with the commits that are approved as-is or with minor changes, for ease of merging.

Did you intentionally drop the change from `$2b` to `$2y` as the default prefix for new hashes?  I was dubious of that change, but I could have been persuaded.

## Commits that are approved as-is

 * [`db1cc32: Lower the minimum required automake version`](https://github.com/besser82/libxcrypt/pull/6/commits/db1cc32b2d7d77b0a089b49a866d264916b41492)
 * [`49a4555: gen-vers.awk: fix typo in comment`](https://github.com/besser82/libxcrypt/pull/6/commits/49a455597e881ca20480338fda2494f243aa166d)
 * [`Fix build with USE_SWAPCONTEXT turned off`](https://github.com/besser82/libxcrypt/pull/6/commits/811a4cbe7d0856ce22ae4fc906f0bf3b9908d135)
 * [`crypt_gensalt_rn: fix the leak of obtained random bytes`](https://github.com/besser82/libxcrypt/pull/6/commits/bea2be2780b7b5c1daa9b10230ff97e776460248)
 * [`test-gensalt: extend checks of expected output`](https://github.com/besser82/libxcrypt/pull/6/commits/e0ac15f89818c6d183c496d7ccbc97dbaa68f1b0)
 * [`Include crypt-port.h in two remaining source files`](https://github.com/besser82/libxcrypt/pull/6/commits/383c633be055b33e2d1d6a6c5ea85e205cd41484)
 * [`Use ARRAY_SIZE instead of open-coding it`](https://github.com/besser82/libxcrypt/pull/6/commits/0c527bc8148afbdee043e9a3f0d32632473e8fc4)

For the record, the minimum automake version was only set that high because I couldn't conveniently test with anything older.

## Commits that are approved with changes

 * [`Extend --enable-weak-hashes configure option`](https://github.com/besser82/libxcrypt/pull/6/commits/28aec701c6c912f2f8dd05c865bd27a225a5a5c3)

   `--enable-weak-hashes=glibc` should also disable bigcrypt support.

   Please make the help string for `--enable-weak-hashes` more specific:

    - When set to "yes", all of the hashing methods documented in
      `crypt(5)` are supported for authenticating existing password
      hashes, including several that are too weak to use for new
      passwords.

    - When set to "glibc", only the weak hashes supported by historic
      versions of GNU libc are supported: traditional DES and
      FreeBSD-style MD5, but not bigcrypt-DES, BSDi extended DES, SHA1,
      SUNMD5, or NTHASH.

    - When set to "no", only bcrypt, SHA512, and SHA256 are supported.
      This mode implies --disable-obsolete-api and breaks binary
      compatibility with glibc's libcrypt.

   This solves issue #7, so please mention that in the commit message.

   (Several of the non-glibc weak hashes are in fact missing from `crypt(5)`, but you don't need to fix that unless you want to.)

 * [`crypt_gensalt_rn: fix the number of automatically obtained random bytes`](https://github.com/besser82/libxcrypt/pull/6/commits/633e59bf7ad8c5f48af4649bdc177349965af74d)

   Please add a comment to the new `nrbytes` field of `struct hashfn`, reading

   ```c
   /* The type of this field is unsigned char to ensure that it cannot
      be set larger than the size of an internal buffer in crypt_gensalt_rn.  */
   ```

 * [`crypt-private.h: use macros for declaring individual hash functions`](https://github.com/besser82/libxcrypt/pull/6/commits/97397d719d3203ca8ab30f9e73279117a41a08d4)

   I appreciate the desire to not have to repeat the rather lengthy argument lists for functions with this signature, but I don't like the idea of not being able to find the prototypes with `grep`.  Instead I suggest that you should move the `crypt_fn` and `gensalt_fn` typedefs from `crypt.c` to `crypt-private.h` and then write e.g.

   ```c
   crypt_fn crypt_sha256_rn;
   crypt_fn crypt_sha512_rn;
   crypt_fn crypt_bcrypt_rn;
   ```

   This will also make it impossible for the prototypes to get out of sync with the typedefs.

 * [`.travis.yml: reduce flakyness`](https://github.com/besser82/libxcrypt/pull/6/commits/d72a16b9cd438b9ddc42a8b3ff96436d9e6f4f5e)

   Please make the retry loops give up after some finite number of iterations, so we don't get in trouble with the Travis sysadmins.

## Commits where we need more information to decide whether it's a good idea

 * [`Rename libxcrypt.pc to libcrypt.pc`](https://github.com/besser82/libxcrypt/pull/6/commits/b4f2d4ff8aa5ec53860defddad2dff8d6e3e3385)

   It would be logical to have the `.pc` file's name match the name of the installed library, but I presume that it was named libxcrypt.pc originally for a good reason, and I don't know what that was.  I'd like @besser82 to comment.

 * [`crypt.h: introduce CRYPT_GENSALT_IMPLEMENTS_* macros`](https://github.com/besser82/libxcrypt/pull/6/commits/d826c396f6e79edbff7367aa5b32983d45f930ef)

   I'm not opposed to adding these but I'd like to know for sure that they will be useful.  Does ALT's version of this header file already provide these macros?  Do programs already exist that look for them?  If not, did someone ask for them?  Also, they should be documented; please add appropriate text to the `crypt_gensalt.3` manpage.

 * [`Extend --enable-obsolete-abi configure option`](https://github.com/besser82/libxcrypt/pull/6/commits/f2ab0fd85282fd94ec58209da9538e58fc80b9c4)

   I don't like the idea of having the set of symbols provided by `libcrypt.so.1` vary from distribution to distribution.  That seems like it will make life harder for people trying to build distro-independent binaries, for no particular benefit.  Does ALT have a concrete reason for _not_ wanting to provide SuSE compatibility?  Again I'd like @besser82 to comment, and if @fweimer has an opinion as integrator for Fedora, I'd like to hear that too.

   In case we do decide to take this patch, please fix the following typo:

        When set to "owl", include interfaces for compatibility with Owl.

   should read

        When set to "owl", include interfaces for compatibility with Openwall.

**Comment by ldv-alt** [comment]
On Fri, Jun 29, 2018 at 01:17:26PM -0700, Zack Weinberg wrote:
> This pull request has a lot of different things mixed up together in it, so I'm going to review commit-by-commit.  I'd appreciate it if you could submit an independent PR with the commits that are approved as-is or with minor changes, for ease of merging.

OK, I've submitted two separate PRs.

> Did you intentionally drop the change from `$2b` to `$2y` as the default prefix for new hashes?  I was dubious of that change, but I could have been persuaded.

Yes, the drop is intentional.  Since we haven't used any default prefix in crypt_gensalt yet, this is not a compatibility issue for us.
Anyway, we are going to move to [yescrypt](http://www.openwall.com/yescrypt/) soon anyway, so this change of default prefix would not last long.
Expect a PR that adds yescrypt support to libxcrypt, likely next week.

>  * [`crypt-private.h: use macros for declaring individual hash functions`](https://github.com/besser82/libxcrypt/pull/6/commits/97397d719d3203ca8ab30f9e73279117a41a08d4)
> 
>    I appreciate the desire to not have to repeat the rather lengthy argument lists for functions with this signature, but I don't like the idea of not being able to find the prototypes with `grep`.  Instead I suggest that you should move the `crypt_fn` and `gensalt_fn` typedefs from `crypt.c` to `crypt-private.h` and then write e.g.
> 
>    ```c
>    crypt_fn crypt_sha256_rn;
>    crypt_fn crypt_sha512_rn;
>    crypt_fn crypt_bcrypt_rn;
>    ```
> 
>    This will also make it impossible for the prototypes to get out of sync with the typedefs.

Unfortunately, this approach doesn't work because these declarations
don't count as function prototypes and the build fails.

> ## Commits where we need more information to decide whether it's a good idea
> 
>  * [`Rename libxcrypt.pc to libcrypt.pc`](https://github.com/besser82/libxcrypt/pull/6/commits/b4f2d4ff8aa5ec53860defddad2dff8d6e3e3385)
> 
>    It would be logical to have the `.pc` file's name match the name of the installed library, but I presume that it was named libxcrypt.pc originally for a good reason, and I don't know what that was.  I'd like @besser82 to comment.

I suppose the original reason was the library name being called libxcrypt.

>  * [`crypt.h: introduce CRYPT_GENSALT_IMPLEMENTS_* macros`](https://github.com/besser82/libxcrypt/pull/6/commits/d826c396f6e79edbff7367aa5b32983d45f930ef)
> 
>    I'm not opposed to adding these but I'd like to know for sure that they will be useful.  Does ALT's version of this header file already provide these macros?  Do programs already exist that look for them?  If not, did someone ask for them?

Yes, we've already started to use them, see e.g. [tcb](http://git.altlinux.org/gears/t/tcb.git?p=tcb.git;a=commitdiff;h=60f031dec9128f1388fa44166d69130554f6d1a0).

>    Also, they should be documented; please add appropriate text to the `crypt_gensalt.3` manpage.

Done.

>  * [`Extend --enable-obsolete-abi configure option`](https://github.com/besser82/libxcrypt/pull/6/commits/f2ab0fd85282fd94ec58209da9538e58fc80b9c4)
> 
>    I don't like the idea of having the set of symbols provided by `libcrypt.so.1` vary from distribution to distribution.  That seems like it will make life harder for people trying to build distro-independent binaries, for no particular benefit.  Does ALT have a concrete reason for _not_ wanting to provide SuSE compatibility?  Again I'd like @besser82 to comment, and if @fweimer has an opinion as integrator for Fedora, I'd like to hear that too.

Sorry, but I do not believe in binary compatibility between incompatible distributions.
Up to this moment all SuSE binaries linked with libxcrypt were incompatible with ALT's libcrypt, and it has never been an issue so far.
I cannot tell for Fedora, but I do not plan to add these interfaces to ALT's libcrypt.
Some day I hope to dump GLIBC_2.0 interface as well.

>    In case we do decide to take this patch, please fix the following typo:
> 
>         When set to "owl", include interfaces for compatibility with Owl.
> 
>    should read
> 
>         When set to "owl", include interfaces for compatibility with Openwall.

This is not a typo.  Owl stands for "Openwall GNU/*/Linux".
When I talk about ABI compatibility, I do not mean the whole Openwall project or its [crypt_blowfish](http://www.openwall.com/crypt/) subproject,
but [the binary distribution](http://www.openwall.com/Owl/).


-- 
ldv

**Comment by besser82** [comment]
Closing here, as further discussion should be done in #9.

**Pull request closed without merging**
