### PR TITLE
Darwin doesn't support strong aliases.

### LINKED ISSUE #43: error: aliases are not supported on darwin
Building libcrypt fails on macOS (a.k.a. Darwin):

```
crypt-des.c:420:1: error: aliases are not supported on darwin
strong_alias (gensalt_des_rn, gensalt_des_big_rn);
^
./crypt-port.h:159:39: note: expanded from macro 'strong_alias'
#define strong_alias(name, aliasname) _strong_alias(name, aliasname)
                                      ^
./crypt-port.h:161:52: note: expanded from macro '_strong_alias'
  extern __typeof (name) aliasname __attribute__ ((alias (#name)))
                                                   ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by besser82**
We need to create the exported symbols using inline asm instead.

Fixes #43.

### CODE REVIEW

**Comment by besser82** [comment]
This can wait until #48 is merged.

**Comment by besser82** [comment]
@zackw With this one merged, I just need to dig into the failing tests…

**Comment by zackw** [comment]
The updated version seems good to me.

**Comment by besser82** [comment]
@zackw FYI, I have rebased and pushed your `endian_replacement` branch on recent `develop`.

**Comment by besser82** [comment]
> Did CI like it then?

Still waiting for it to finish.  Failures on macOS are not that important.  I'll fix them after it was merged.

https://travis-ci.org/besser82/libxcrypt/builds/449109104

**Pull request merged**
