### PR TITLE
Setup github actions CI

### PR DESCRIPTION
**Pull request by besser82**
As the free TravisCI is going to pass away in near future, we should adopt our CI to github actions.

### CODE REVIEW

**Comment by zackw** [comment]
+1 from me on the idea.  The last time I did any serious work on libxcrypt, Travis was quite unreliable and it slowed me down.

**Comment by zackw** [comment]
@besser82 Can you please give me access to the Codecov pages for this project?

**Comment by besser82** [comment]
> @besser82 Can you please give me access to the Codecov pages for this project?

You should already have access, given you are using your Github account to login to Codecov.

From Codecov settings:

> Codecov uses GitHub permissions to authenticate users. No setup necessary.
>
> Ask your team members to login to Codecov and they will have read/write access to the appropriate repositories.

**Comment by zackw** [comment]
@besser82 You're right, I do have access.  I was confused because I couldn't find it from my codecov dash (because that only shows my personal repos + *organizational* repos I have access to).

**Comment by zackw** [comment]
FYI, [this codecov link](https://app.codecov.io/gh/besser82/libxcrypt/compare/1e793892f46196458a63ffe8bde909f248165725...ff1bfae58b5fa9bfd53f6acdaffcd09274ad6fc6/changes) will show a reasonably accurate comparison between the coverage we used to get with TravisCI (commit 1e793892f46196458a63ffe8bde909f248165725) and the coverage we are currently getting with the minimalist GHA configuration on trunk (commit ff1bfae58b5fa9bfd53f6acdaffcd09274ad6fc6).  The coverage comparison posted at the top of this PR's history _starts from_ ff1bfae58b5fa9bfd53f6acdaffcd09274ad6fc6.

**Comment by zackw** [comment]
@besser82 In order to get Coverity working again, I need you to establish the same CI secrets for Github Actions as we had for Travis: `COVERITY_SCAN_NOTIFICATION_EMAIL` and `COVERITY_SCAN_TOKEN`.  Since the project is on your personal Github account, only you can do this.

**Comment by besser82** [comment]
> @besser82 In order to get Coverity working again, I need you to establish the same CI secrets for Github Actions as we had for Travis: `COVERITY_SCAN_NOTIFICATION_EMAIL` and `COVERITY_SCAN_TOKEN`. Since the project is on your personal Github account, only you can do this.

They should be set properly already.


> Relatedly, there's a warning on deepcode.ai about needing to migrate to the successor service, snyk, and again I think only you can do this (it involves messing with the webhooks).

I will look into this in short time.

**Comment by zackw** [comment]
well, that only took all bloody afternoon, but coverity works again.

**Comment by besser82** [comment]
LGTM!

@zackw Thanks for your further work on this, as I had very little spare time in last weeks.

**Comment by zackw** [comment]
@besser82 Excellent timing! I have run out of time to work on this until probably next month. 

I believe the only thing left to port over from the Travis configuration is MacOS builds, and I don't know how important those really are (it _is_ nice to get testing on something that isn't Linux, though).  Should we go ahead and land this and add those later?

There's also a bunch of potential refinements we could make -- less repetition, more linting, etc -- but I think we shouldn't wait for those.

**Comment by besser82** [comment]
@zackw I'm totally fine with landing this in `develop`.  We can add further refinements and OSX related things with later PRs / commits.

Let me just squash my last commit and I'll merge this on cli.

**Comment by besser82** [comment]
Merged with 9011b0b.

**Pull request closed without merging**
