### PR TITLE
Implement the crypt_preferred_method function.

### PR DESCRIPTION
**Pull request by besser82**
crypt_preferred_method(3) is a convenience function to get the prefix of the preferred hash method.  If a preferred method is available, it is the same as the one also used by the crypt_gensalt functions, if their given prefix parameter is NULL.

If no preferred hash method is supported, the return value of this function is NULL.

### CODE REVIEW

**Comment by zackw** [comment]
This seems like a fine addition and I don't see any problems with the code.

**Comment by besser82** [comment]
@zackw The documentation is fine, too?  Or does it need any changes / improvements?

**Comment by zackw** [comment]
I'm not entirely happy with the bit that goes

> ```nroff
> If no preferred hash method is available it is NULL.  It
> .Em is
> safe to pass the string returned by
> .Nm crypt_preferred_method
> directly to
> .Nm crypt_gensalt .
> ```

because that makes it sound like there might be a thread-safety issue, even though there isn't.  But I haven't been able to think of a better phrasing and I don't think it should block the merge.  We can always improve the manpage later.

**Comment by besser82** [comment]
> I'm not entirely happy with the bit that goes
> 
> > ```
> > If no preferred hash method is available it is NULL.  It
> > .Em is
> > safe to pass the string returned by
> > .Nm crypt_preferred_method
> > directly to
> > .Nm crypt_gensalt .
> > ```
> 
> because that makes it sound like there might be a thread-safety issue, even though there isn't. But I haven't been able to think of a better phrasing and I don't think it should block the merge. We can always improve the manpage later.
> 
> Otherwise the new docs look fine to me.

@zackw Maybe this sounds better?

> ```
> If no preferred hash method is available it is NULL.  It
> .Em is
> safe to pass the string returned by
> .Nm crypt_preferred_method
> directly to
> .Nm crypt_gensalt
> without prior string-sanitizing nor NULL-pointer checks.
> ```

**Pull request merged**
