### PR TITLE
yescrypt: split smix1 and smix2 into functions for each subcase.

### PR DESCRIPTION
**Pull request by zackw**
smix’s subroutines smix1 and smix2 both do some setup work, then perform one of several different operations depending on the precise combination of arguments they were passed, and then some teardown work.  Some combinations of arguments are not possible but would cause crashes if they were possible.  Static analysis has trouble proving that these combinations are not possible.

Split up both subroutines into separate functions for each of the possible operations (smix1_rom, smix1_rw, smix1_worm; smix2_rom, smix2_romro, smix2_rw, smix2_rwro, smix2_worm).  The NROM, VROM, and ctx arguments are only supplied to the subroutines that will actually use them, and flags is supplied to none of them.  The shared setup and teardown work is factored out to helper routines smix_init and smix_final. All of the “which case are we in?” logic is consolidated into smix itself.

This should be more legible to both static analysis programs and human understanding.  Specifically, I believe it will resolve the Coverity defect report that ctx could be dereferenced while it was NULL.  However, I don't think libxcrypt's test suite covers all of the cases that are affected (since we don't ever use ROMs or p>1) and it's a significant enough change that I don't think we should merge it without yescrypt upstream agreeing to take it as well.

I would like @solardiz to review this change but I do not seem to be able to officially request that through the Github interface.

### CODE REVIEW

**Comment by solardiz** [comment]
Thanks, but this appears to add 167 lines of code and probably makes further maintenance harder and has unclear to me effect on "human understanding". I think this shouldn't be merged as-is, but I'd like to revisit these changes and maybe cherry-pick some ideas when I try to simplify upstream code and make it friendlier to static analysis. I might reuse the smix_init and smix_final concept - in fact, I've already been thinking that it might be simpler to do those things at top smix rather than smix1/smix2 level.

**Comment by zackw** [comment]
OK, understood.  I'm not going to pursue this any further myself.  Please
let us know if and when you have a change that you're happy with that might
address the issue.

**Comment by besser82** [comment]
@zackw @solardiz For the time until this is fixed in some way, I've added special annotations for Coverity Scan in https://github.com/besser82/libxcrypt/commit/42a22323a0267da38fffd873246e08950423753c.

**Comment by solardiz** [comment]
@besser82 The annotations for Coverity are OK with me for now, thanks!

**Pull request closed without merging**
